name: Label prs based on reviews
on: [pull_request_review, pull_request_review_comment]

jobs:
  label_pr_when_approved:
    runs-on: ubuntu-latest
    name: A job to label prs according with approvals
    steps:
      - name: Label a pr when approved
        id: approved
        uses: lightspeedretail/actions-label-prs@v1
        with:
          task: 'label_pr_when_approved'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPROVALS: "1"
          ADD_LABEL: "approved"
